# Generated by Django 5.0 on 2024-01-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wish',
            options={'verbose_name': 'Желание', 'verbose_name_plural': 'Желания'},
        ),
        migrations.AlterField(
            model_name='wish',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='image',
            field=models.ImageField(upload_to='uploads', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
